import './auth.css'
import Image, {StaticImageData} from "next/image";
import Kodix from "../../../public/svg/kodix.svg";
import {Inter} from "next/font/google";

const inter = Inter({
    subsets: ['latin'],
});

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col justify-center items-center gap-[40px] h-[100vh]">
        <Image src={Kodix as StaticImageData} alt="kodix logo" width={240} height={42}></Image>
        {children}
      </div>
      </body>
    </html>
  )
}
