import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header/Header";
import { Inter } from "next/font/google";

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={`${inter.className} antialiased`}
    >
    <Header></Header>
    <div className="gradient-circle-left"></div>
    <div className="gradient-circle-right"></div>
    {children}
    </body>
    </html>
  );
}
